//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auxil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=|DataDirectory|\\Auxil.accdb")]
        public string AuxilConnectionString {
            get {
                return ((string)(this["AuxilConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\i336796\\Documents\\R\\Util\\Processos.db3")]
        public string Processos {
            get {
                return ((string)(this["Processos"]));
            }
            set {
                this["Processos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public short QuantAreaTransf {
            get {
                return ((short)(this["QuantAreaTransf"]));
            }
            set {
                this["QuantAreaTransf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("312")]
        public int LarguraTela {
            get {
                return ((int)(this["LarguraTela"]));
            }
            set {
                this["LarguraTela"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148")]
        public int AlturaTela {
            get {
                return ((int)(this["AlturaTela"]));
            }
            set {
                this["AlturaTela"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OrdenarLista {
            get {
                return ((bool)(this["OrdenarLista"]));
            }
            set {
                this["OrdenarLista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\i336796\\Documents\\R\\INI\'s\\Util\\AreaTransf.ini")]
        public string CaminhoTextoAreaTransf {
            get {
                return ((string)(this["CaminhoTextoAreaTransf"]));
            }
            set {
                this["CaminhoTextoAreaTransf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ListaMaiusculo {
            get {
                return ((bool)(this["ListaMaiusculo"]));
            }
            set {
                this["ListaMaiusculo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\Projetos\\GD4253S477\\Auxil\\ProcessosCompart.db3")]
        public string ProcessosRede {
            get {
                return ((string)(this["ProcessosRede"]));
            }
            set {
                this["ProcessosRede"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\i336796\\Documents\\R\\P\\CentralizadorDados\\CentralizadorDados\\bin\\Release\\" +
            "CentralizadorDados.exe")]
        public string CentralDados {
            get {
                return ((string)(this["CentralDados"]));
            }
            set {
                this["CentralDados"] = value;
            }
        }
    }
}
